//service
$(document).ready(function(){
    $('.detail-link1-tab').addClass('text-pink'),
    $('.link1-tab').click(function(){
        $('.detail-link1-tab').addClass('text-pink'),
        $('.detail-link2-tab').removeClass('text-pink'),
        $('.detail-link3-tab').removeClass('text-pink'),
        $('.detail-link4-tab').removeClass('text-pink'),
        $('.detail-link5-tab').removeClass('text-pink');
    }),
    $('.link2-tab').click(function(){
        $('.detail-link2-tab').addClass('text-pink'),
        $('.detail-link1-tab').removeClass('text-pink'),
        $('.detail-link3-tab').removeClass('text-pink'),
        $('.detail-link4-tab').removeClass('text-pink'),
        $('.detail-link5-tab').removeClass('text-pink');
    }),
    $('.link3-tab').click(function(){
        $('.detail-link3-tab').addClass('text-pink'),
        $('.detail-link1-tab').removeClass('text-pink'),
        $('.detail-link2-tab').removeClass('text-pink'),
        $('.detail-link4-tab').removeClass('text-pink'),
        $('.detail-link5-tab').removeClass('text-pink');
    }),
    $('.link4-tab').click(function(){
        $('.detail-link4-tab').addClass('text-pink'),
        $('.detail-link1-tab').removeClass('text-pink'),
        $('.detail-link2-tab').removeClass('text-pink'),
        $('.detail-link3-tab').removeClass('text-pink'),
        $('.detail-link5-tab').removeClass('text-pink');
    }),
    $('.link5-tab').click(function(){
        $('.detail-link5-tab').addClass('text-pink'),
        $('.detail-link1-tab').removeClass('text-pink'),
        $('.detail-link2-tab').removeClass('text-pink'),
        $('.detail-link3-tab').removeClass('text-pink'),
        $('.detail-link4-tab').removeClass('text-pink');
    })
})
$(document).ready(function(){
    $('.box0').mouseenter(function(){
        $('.box1').css('transform','rotateZ(360deg)');
    }),
    $('.box00').mouseenter(function(){
        $('.box2').css('transform','rotateZ(360deg)');
    }),
    $('.box000').mouseenter(function(){
        $('.box3').css('transform','rotateZ(360deg)');
    }),
    $('.box0000').mouseenter(function(){
        $('.box4').css('transform','rotateZ(360deg)');
    })
})
//work
$(document).ready(function(){
    $('.box1-work').mouseenter(function(){
        $('.over1').fadeTo('slow',1);
    }),
    $('.box1-work').mouseleave(function(){
        $('.over1').fadeTo('slow',0);
    }),
    $('.box2-work').mouseenter(function(){
        $('.over2').fadeTo('slow',1);
    }),
    $('.box2-work').mouseleave(function(){
        $('.over2').fadeTo('slow',0);
    }),
    $('.box3-work').mouseenter(function(){
        $('.over3').fadeTo('slow',1);
    }),
    $('.box3-work').mouseleave(function(){
        $('.over3').fadeTo('slow',0);
    }),
    $('.box4-work').mouseenter(function(){
        $('.over4').fadeTo('slow',1);
    }),
    $('.box4-work').mouseleave(function(){
        $('.over4').fadeTo('slow',0);
    }),
    $('.box5-work').mouseenter(function(){
        $('.over5').fadeTo('slow',1);
    }),
    $('.box5-work').mouseleave(function(){
        $('.over5').fadeTo('slow',0);
    }),
    $('.box6-work').mouseenter(function(){
        $('.over6').fadeTo('slow',1);
    }),
    $('.box6-work').mouseleave(function(){
        $('.over6').fadeTo('slow',0);
    }),
    $('.box7-work').mouseenter(function(){
        $('.over7').fadeTo('slow',1);
    }),
    $('.box7-work').mouseleave(function(){
        $('.over7').fadeTo('slow',0);
    }),
    $('.box8-work').mouseenter(function(){
        $('.over8').fadeTo('slow',1);
    }),
    $('.box8-work').mouseleave(function(){
        $('.over8').fadeTo('slow',0);
    }),
    $('.box9-work').mouseenter(function(){
        $('.over9').fadeTo('slow',1);
    }),
    $('.box9-work').mouseleave(function(){
        $('.over9').fadeTo('slow',0);
    });
})